package Cine.view;

import Cine.control.ClickedListener;



public class HomeFrame extends javax.swing.JFrame
{

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame()
    {
        initComponents();
        uLabel1.setDestFrame("NextFrame");
        uLabel1.setType("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        uMovieLabel3 = new Cine.view_components.UMovieLabel();
        Featured_Label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        uMovieLabel4 = new Cine.view_components.UMovieLabel();
        jPanel5 = new javax.swing.JPanel();
        uMovieLabel2 = new Cine.view_components.UMovieLabel();
        uLabel1 = new Cine.view_components.ULabel();
        uLabel2 = new Cine.view_components.ULabel();
        uLabel3 = new Cine.view_components.ULabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Description_Movie1 = new javax.swing.JLabel();
        Title_Movie1 = new javax.swing.JLabel();
        Content_Movie1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uMovieLabel1 = new Cine.view_components.UMovieLabel();
        Line = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Line1 = new javax.swing.JLabel();
        InsideBox_Title = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        uMovieLabel5 = new Cine.view_components.UMovieLabel();
        Note = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        Line7 = new javax.swing.JLabel();
        Line3 = new javax.swing.JLabel();
        Line4 = new javax.swing.JLabel();
        Line5 = new javax.swing.JLabel();
        Line6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        Title_Movie2 = new javax.swing.JLabel();
        Content_Movie2 = new javax.swing.JLabel();
        Description_Movie2 = new javax.swing.JLabel();
        Title_Movie3 = new javax.swing.JLabel();
        Content_Movie3 = new javax.swing.JLabel();
        Description_Movie3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(600, 360));
        setResizable(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uMovieLabel3.setText("uMovieLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(729, Short.MAX_VALUE)
                .addComponent(uMovieLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(uMovieLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1030, -1, -1));

        Featured_Label.setBackground(new java.awt.Color(255, 255, 255));
        Featured_Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Featured_Label.setForeground(new java.awt.Color(255, 255, 255));
        Featured_Label.setText("Top Picks");
        jPanel1.add(Featured_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, -1));

        uMovieLabel4.setText("uMovieLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(739, Short.MAX_VALUE)
                .addComponent(uMovieLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(uMovieLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1345, -1, -1));

        uMovieLabel2.setText("uMovieLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(uMovieLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(uMovieLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 713, -1, -1));

        uLabel1.setForeground(new java.awt.Color(255, 255, 255));
        uLabel1.setText("Home");
        jPanel1.add(uLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 40, -1, -1));

        uLabel2.setForeground(new java.awt.Color(255, 255, 255));
        uLabel2.setText("Log in");
        jPanel1.add(uLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 40, -1, -1));

        uLabel3.setForeground(new java.awt.Color(255, 255, 255));
        uLabel3.setText("Sign up");
        jPanel1.add(uLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 40, -1, -1));

        jLabel1.setText("Disclaimer:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(1506, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3740, 1590, 70));

        Description_Movie1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Description_Movie1.setForeground(new java.awt.Color(255, 255, 255));
        Description_Movie1.setText("<html>\nAfter the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.\n</html>");
        Description_Movie1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Description_Movie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 800, 350, 180));

        Title_Movie1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        Title_Movie1.setForeground(new java.awt.Color(255, 255, 255));
        Title_Movie1.setText("Avengers: Endgame");
        jPanel1.add(Title_Movie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 710, -1, -1));

        Content_Movie1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Content_Movie1.setForeground(new java.awt.Color(255, 255, 255));
        Content_Movie1.setText("PG-13 2019 | Action/Adventure | 3h 1m");
        jPanel1.add(Content_Movie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 780, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEENEMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 249, 55));

        uMovieLabel1.setText("uMovieLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(698, 698, 698)
                .addComponent(uMovieLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(826, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(uMovieLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1600, -1));

        Line.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line.setForeground(new java.awt.Color(255, 255, 255));
        Line.setText("_____________");
        jPanel1.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 270, -1));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Line1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line1.setForeground(new java.awt.Color(255, 255, 255));
        Line1.setText("________________");
        jPanel11.add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 330, 60));

        InsideBox_Title.setBackground(new java.awt.Color(255, 255, 255));
        InsideBox_Title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 60)); // NOI18N
        InsideBox_Title.setForeground(new java.awt.Color(255, 255, 255));
        InsideBox_Title.setText("SEENEMA");
        jPanel11.add(InsideBox_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 290, 60));

        uMovieLabel5.setText("uMovieLabel5");

        Note.setText("GIF of CInema theater with movies");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(uMovieLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Note)
                        .addGap(103, 103, 103))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Note)
                .addGap(46, 46, 46)
                .addComponent(uMovieLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 410, 350));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("<html>\n<center>\nFeatures: • IMAX w/ Laser • Dolby Atmos • Laser Projection • MX4D Theater • VIP Theater\n</center>\n</html>");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 430, 102));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1760, 1020, 350));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1325, 1750, 3, 350));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1345, 1740, 3, 340));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1315, 1750, 3, 360));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 1750, 3, 340));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1355, 1740, -1, 330));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1365, 1740, -1, 320));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1385, 1730, -1, 310));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1375, 1730, -1, -1));

        jPanel10.setBackground(new java.awt.Color(137, 129, 150));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>\n<center>\n IMAX with Laser is the next-generation in 4k laser projection systems, featuring a new optical engine and suite of proprietary IMAX technologies that delivers increased resolution, sharper and brighter images, deeper contrast as well as the widest range of colors available to filmmakers to present more distinct, exotic colors than ever before. The new system also features IMAX’s 12-channel sound technology that incorporates new side and overheard channels to deliver greater dynamic range and precision for ultimate audio immersion and sound you can feel. \n</center>\n</html>");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 800, 270));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel6.setText("\nIMAX WITH LASER\n");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 890, 300));

        Line7.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line7.setText("_____________________________________________");
        jPanel10.add(Line7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1990, 1600, 870));

        Line3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line3.setForeground(new java.awt.Color(255, 255, 255));
        Line3.setText("___________________________________________________");
        jPanel1.add(Line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1710, 1020, -1));

        Line4.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line4.setForeground(new java.awt.Color(255, 255, 255));
        Line4.setText("_____________________________________________________");
        jPanel1.add(Line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1677, 1110, 60));

        Line5.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line5.setForeground(new java.awt.Color(255, 255, 255));
        Line5.setText("_____________________________________________________");
        jPanel1.add(Line5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1680, 1130, 70));

        Line6.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Line6.setForeground(new java.awt.Color(255, 255, 255));
        Line6.setText("____________________________________________________");
        jPanel1.add(Line6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1700, 1090, -1));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2930, 820, 270));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>\n<center>\nLaser Projection Technology With Vista Cinemas anyone can have a great, enjoyable, and memorable movie experience. We also use the latest projection technology to showcase movies with crystal clear definition!\n</center>\n</html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 3320, 340, 240));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(137, 129, 150));
        jLabel8.setText("<html>  <center> C I N E M A </center> </html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 3250, 140, 90));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(137, 129, 150));
        jLabel7.setText("<html>  <center> MUCH MORE THAN A BIG SCREEN </center> </html>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 3490, 390, 40));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html> <center> Dolby Atmos Transports you into the story with moving audio that flows all around you with breathtaking realism. Have a powerfully moving entertainment experience in our cinemas. </center> </html>");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 3280, 300, 180));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 3250, 3, -1));

        Title_Movie2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        Title_Movie2.setForeground(new java.awt.Color(255, 255, 255));
        Title_Movie2.setText("Avengers: Endgame");
        jPanel1.add(Title_Movie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1020, -1, -1));

        Content_Movie2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Content_Movie2.setForeground(new java.awt.Color(255, 255, 255));
        Content_Movie2.setText("PG-13 2019 | Action/Adventure | 3h 1m");
        jPanel1.add(Content_Movie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1090, -1, -1));

        Description_Movie2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Description_Movie2.setForeground(new java.awt.Color(255, 255, 255));
        Description_Movie2.setText("<html>\nAfter the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.\n</html>");
        Description_Movie2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Description_Movie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1110, 350, 180));

        Title_Movie3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        Title_Movie3.setForeground(new java.awt.Color(255, 255, 255));
        Title_Movie3.setText("Avengers: Endgame");
        jPanel1.add(Title_Movie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1350, -1, -1));

        Content_Movie3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Content_Movie3.setForeground(new java.awt.Color(255, 255, 255));
        Content_Movie3.setText("PG-13 2019 | Action/Adventure | 3h 1m");
        jPanel1.add(Content_Movie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1420, -1, -1));

        Description_Movie3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Description_Movie3.setForeground(new java.awt.Color(255, 255, 255));
        Description_Movie3.setText("<html>\nAfter the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.\n</html>");
        Description_Movie3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Description_Movie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1440, 350, 180));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Content_Movie1;
    private javax.swing.JLabel Content_Movie2;
    private javax.swing.JLabel Content_Movie3;
    private javax.swing.JLabel Description_Movie1;
    private javax.swing.JLabel Description_Movie2;
    private javax.swing.JLabel Description_Movie3;
    private javax.swing.JLabel Featured_Label;
    private javax.swing.JLabel InsideBox_Title;
    private javax.swing.JLabel Line;
    private javax.swing.JLabel Line1;
    private javax.swing.JLabel Line3;
    private javax.swing.JLabel Line4;
    private javax.swing.JLabel Line5;
    private javax.swing.JLabel Line6;
    private javax.swing.JLabel Line7;
    private javax.swing.JLabel Note;
    private javax.swing.JLabel Title_Movie1;
    private javax.swing.JLabel Title_Movie2;
    private javax.swing.JLabel Title_Movie3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Cine.view_components.ULabel uLabel1;
    private Cine.view_components.ULabel uLabel2;
    private Cine.view_components.ULabel uLabel3;
    private Cine.view_components.UMovieLabel uMovieLabel1;
    private Cine.view_components.UMovieLabel uMovieLabel2;
    private Cine.view_components.UMovieLabel uMovieLabel3;
    private Cine.view_components.UMovieLabel uMovieLabel4;
    private Cine.view_components.UMovieLabel uMovieLabel5;
    // End of variables declaration//GEN-END:variables
}
